name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew
        working-directory: ./cs203system
#      - name: Build with Gradle
#        run: ./gradlew build
#        working-directory: ./cs203system
      - name: Build the Docker image
        run: docker build --file Dockerfile \
            --build-arg DB_HOST=${DATASOURCE_URL} \
            --build-arg DB_USER=${DATASOURCE_USERNAME} \
            --build-arg DB_PASSWORD=${DATASOURCE_PASSWORD} \
            --tag cs203someshit/aws-cicd:${{ github.sha }} .
        working-directory: ./cs203system
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to docker hub
        run: docker push cs203someshit/aws-cicd:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull from docker hub
        run: docker pull cs203someshit/aws-cicd:${{ github.sha }}
      - name: Stop and remove existing container (if running)
        run: |
          docker stop spring-app-container || true
          docker rm spring-app-container || true
      - name: Run docker container
        run: |
          docker run -d -p 8080:8080 \
            --name spring-app-container \
            cs203someshit/aws-cicd:${{ github.sha }}

